### ISSUE TITLE
Discrepancy with Kneadata

### ISSUE THREAD

**Issue by akhst7** [GenomePathogenAnalysisService/read-it-and-keep#13]
Hi, 

I have trimmed 16S PE reads from mouse lung and used read-it-and-keep to remove potentially contaminating mouse genome by a following command;

```
readItAndKeep --ref_fasta /Volumes/Aura/Mus_musculus.GRCm39.dna.primary_assembly.fa \
 --reads1 trimmed_255-001_S1_L001_R1_001.fastq --reads2 trimmed_255-001_S1_L001_R2_001.fastq -o out
```
The output of the result is as follows;

```
Processed 100000 reads (or read pairs)
Processed 200000 reads (or read pairs)
Input reads file 1	272955
Input reads file 2	272955
Kept reads 1	27
Kept reads 2	27
```
It kept only 27 reads down from 272955.  

As a comparison, I used kneaddata from Huttonhower lab.  I used a following command on the same PE read with the exact same ref genomic database;  

`kneaddata --input1 trimmed_255-001_S1_L001_R1_001.fastq --input2 trimmed_255-001_S1_L001_R2_001.fastq -db /Volumes/Aura/bowtie_GRCm39_DB --output kneaddata_output -t 12 --bypass-trim --bypass-trf`

A result is as follows;

```
7.0K May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata.log
0B May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_GRcm39DB_bowtie2_paired_contam_1.fastq
0B May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_GRcm39DB_bowtie2_paired_contam_2.fastq
46K May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_GRcm39DB_bowtie2_unmatched_1_contam.fastq
68K May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_GRcm39DB_bowtie2_unmatched_2_contam.fastq
0B May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_paired_1.fastq
0B May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_paired_2.fastq
148M May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_unmatched_1.fastq
148M May  4 14:17 trimmed_255-001_S1_L001_R1_001_kneaddata_unmatched_2.fastq
```
As you can see, keaddata did not remove any sequence.   So why read-it-and-keep kept fewer reads after decom with the mouse genome ? 

Should read-it-and-keep not be used for decontamination of the host genome in any microbiome samples other than SARAS2  or other virus ? 

Thanks.

**Comment by martinghunt** [comment]
ReadItAndKeep works by keeping reads that match the provided genome fasta. I think you've run it expecting it to remove reads that match the provided genome? Sorry this wasn't clear from the readme - I've added in a sentence to say that now.

I wouldn't recommend using this for microbiome samples, because you'd have to make a target fasta of everything you want to keep.

**Comment by akhst7** [comment]
@martinghunt,  I got it.  I sort of suspected this but.  So I have to take those matches sequences that are kept in out files from the original.  It will be super if readitandkeep generates two sets of output files, ones with matched genomic sequences and others with sequences minus host genomic sequences.  

Anyway,  I am not sure what you meant by "a target fasta of everything you want to keep" but I've tested  readitandkeep with several of our microbiome fastqs with moderate to sever host genome (mouse and human) contamination, and I have to say it performs comparable to or better than  other similar apps.

**Comment by iqbal-lab** [comment]
Hi there- i just want to make sure we understand each other. The intention of RIAK is that it's for situations where you know the species you want to retain. You want to exclude everything except one thing, and that thing should be relatively low diversity, so that mapping to that reference it a good way of detecting all reads from the species. This is really designed and tested for sars-cov-2. If you want to detect SC2 within metagenomic datasets, it might well work (but potentially might hit non-human coronaviruses, i don't know). If you are using it for general metagenomic datasets, and want to pull out E coli or whatever and exclude mouse, I would not recommend it. 

Does that match with your understanding? Could you clarify what you're using it for? (I'm only asking just to make sure RIAK is appropriate to you, not trying to find anything private)

**Comment by iqbal-lab** [comment]
So, for SC2, we want to exclude everything except SC2, so we use it mapping to the SC2 reference (minus polyA tail), and thereby exclude human and other stuff.

**Comment by akhst7** [comment]
@iqbal-lab   Thanks for the clarification. Just curiosity, what is accuracy of RIKA picking  reads that match against human or mouse ref genomes, as compared to the  SC2 ref genome ?

**Comment by iqbal-lab** [comment]
No idea about mouse,  check out our paper

https://www.biorxiv.org/content/10.1101/2022.01.21.477194v1.full

100% removal of human reads if map to SC2 (with polyA removed,  as RIAK does). 
Mapping to human is not guaranteed to remove human, especially with nanopore data.

**Comment by akhst7** [comment]
Thanks.
